name: MIR_project
channels:
  - conda-forge
  - pypi
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit
  - ipython
  - ipykernel
  - jupyter
  - matplotlib
  - librosa
  - pandas
  - scikit-learn
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - torch-summary
