name: music_analysis_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - scikit-learn=0.24
  - numpy=1.18.*
  - tensorflow
  - pandas=1.2.2
  - matplotlib
  - seaborn
  - librosa
  - jupyter
  - gast=0.3.3
  - opt-einsum=2.3.2
  - scipy=1.4.1
  - tensorflow-estimator=2.3.0
  - bleach=1.5.0
  - html5lib=0.*
  - pip
  - pip:
    - tensorflow-datasets
    - fire==0.4.0
    - googledrivedownloader==0.4
    - solos==0.4.1
    - termcolor==1.1.0
    - youtube-dl==2021.1.24.1
